In [1]:
import pandas as pd
import cvxpy as cp
import numpy as np
from numpy import random
import math

# File path will be different on another device and must be replaced with the correct file path.
students = pd.read_csv("Sample Data (for scheduling) - Students.csv")
print(students.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Student ID       60 non-null     int64 
 1   First Name       60 non-null     object
 2   Last Name        60 non-null     object
 3   Gender           60 non-null     object
 4   Age              60 non-null     int64 
 5   Times Available  60 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.9+ KB
None


In [2]:
random.seed(3230)
num_teachers = 14 # Say we have 14 available teachers in total.
ids = list(range(0, num_teachers))
num_elem = 0
grade = []
for i in range(num_teachers):
    g = random.choice(["elem", "ms"])
    if (num_elem < 5): # Say we have 5 of those teachers are elementary teachers only.
        grade.append(g)
        if (g == "elem"):
            num_elem = num_elem + 1
    else:
        grade.append("ms")     
certificate = random.choice([0,1], size=num_teachers)
teachers = pd.DataFrame({'Teacher ID': ids, 'Grade': grade, 'Certificate': certificate})
display(teachers)

Teacher ID Grade  Certificate
0            0  elem            1
1            1  elem            0
2            2    ms            1
3            3    ms            0
4            4  elem            1
5            5  elem            0
6            6  elem            0
7            7    ms            1
8            8    ms            0
9            9    ms            0
10          10    ms            0
11          11    ms            1
12          12    ms            0
13          13    ms            1

In [3]:
students['Age'].value_counts()

Age
9     13
12    12
11    11
13     9
8      8
10     7
Name: count, dtype: int64

In [4]:
# Reference: https://www.geeksforgeeks.org/create-a-new-column-in-pandas-dataframe-based-on-the-existing-columns/
def grade(age):
    if age > 11:
        return "elem"
    else:
        return "ms"

students['Grade'] = students['Age'].map(grade)
display(students.head())

Student ID First Name Last Name Gender  Age Times Available Grade
0           0     Ximeno   Colombo      M    9    [1, 2, 3, 4]    ms
1           1   Dorothea   Clayton      F    9       [1, 3, 4]    ms
2           2   Beibhinn       Nye      F   13       [1, 2, 3]  elem
3           3      Oskar   Ciobanu      M   12    [1, 2, 3, 4]  elem
4           4    Matilda   Solomon      F   11          [2, 3]    ms

In [5]:
firstHour = []
secondHour = []
thirdHour = []
fourthHour = []

for i in students['Times Available']:
    x = []
    for j in i:
        if j.isdigit(): # Reference: https://www.w3schools.com/python/ref_string_isdigit.asp
            x.append(int(j))
    if 1 in x:
        firstHour.append(1)
    else:
        firstHour.append(0)
    if 2 in x:
        secondHour.append(1)
    else:
        secondHour.append(0)
    if 3 in x:
        thirdHour.append(1)
    else:
        thirdHour.append(0)
    if 4 in x:
        fourthHour.append(1)
    else:
        fourthHour.append(0)

In [6]:
# Reference: https://www.geeksforgeeks.org/add-multiple-columns-to-dataframe-in-pandas/
students['First Hour'] = firstHour
students['Second Hour'] = secondHour
students['Third Hour'] = thirdHour
students['Fourth Hour'] = fourthHour

In [7]:
display(students.head())

Student ID First Name Last Name Gender  Age Times Available Grade  \
0           0     Ximeno   Colombo      M    9    [1, 2, 3, 4]    ms   
1           1   Dorothea   Clayton      F    9       [1, 3, 4]    ms   
2           2   Beibhinn       Nye      F   13       [1, 2, 3]  elem   
3           3      Oskar   Ciobanu      M   12    [1, 2, 3, 4]  elem   
4           4    Matilda   Solomon      F   11          [2, 3]    ms   

   First Hour  Second Hour  Third Hour  Fourth Hour  
0           1            1           1            1  
1           1            0           1            1  
2           1            1           1            0  
3           1            1           1            1  
4           0            1           1            0

In [8]:
random.seed(3230)
trouble = random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], size=len(students)) # Reference: https://www.w3schools.com/python/numpy/numpy_random.asp
students['Trouble'] = trouble # Reference: https://www.geeksforgeeks.org/adding-new-column-to-existing-dataframe-in-pandas/
def percentage_disability(N, chance):
    disability = []
    for i in range(N):
        # Reference: https://stackoverflow.com/questions/3203099/percentage-chance-to-make-action
        disability.append(math.floor( random.uniform(0, 1/(1-chance)) ))
    return(disability)
students['Disability'] = percentage_disability(len(students), 0.05)
# According to https://www.census.gov/content/dam/Census/library/publications/2021/acs/acsbr-006.pdf, around 5% of children have a disability.
random.choice([0,1], size=len(students))

teachers['Relief'] = random.choice([5, 6, 7, 8, 9, 10], size=len(teachers))

In [9]:
display(students.head())

Student ID First Name Last Name Gender  Age Times Available Grade  \
0           0     Ximeno   Colombo      M    9    [1, 2, 3, 4]    ms   
1           1   Dorothea   Clayton      F    9       [1, 3, 4]    ms   
2           2   Beibhinn       Nye      F   13       [1, 2, 3]  elem   
3           3      Oskar   Ciobanu      M   12    [1, 2, 3, 4]  elem   
4           4    Matilda   Solomon      F   11          [2, 3]    ms   

   First Hour  Second Hour  Third Hour  Fourth Hour  Trouble  Disability  
0           1            1           1            1       10           0  
1           1            0           1            1       10           0  
2           1            1           1            0        7           0  
3           1            1           1            1        6           0  
4           0            1           1            0        7           0

In [10]:
display(teachers.head())

Teacher ID Grade  Certificate  Relief
0           0  elem            1       9
1           1  elem            0       5
2           2    ms            1       7
3           3    ms            0      10
4           4  elem            1       9

In [11]:
# Reference: https://www.geeksforgeeks.org/split-pandas-dataframe-by-column-value/
elementary = students[students['Grade'] == "elem"]
middle = students[students['Grade'] == "ms"]
# Reference: https://www.geeksforgeeks.org/python-delete-rows-columns-from-dataframe-using-pandas-drop/
elementary = elementary.drop(['Gender', 'Age', 'Times Available', 'Grade'], axis = 1)
middle = middle.drop(['Gender', 'Age', 'Times Available', 'Grade'], axis = 1)

In [12]:
display(elementary.head())

Student ID First Name   Last Name  First Hour  Second Hour  Third Hour  \
2            2   Beibhinn         Nye           1            1           1   
3            3      Oskar     Ciobanu           1            1           1   
6            6    Liupold  Gunnarsson           1            1           0   
7            7   Venancio       Vanev           1            1           1   
10          10   Jayadeva       Abbas           1            1           1   

    Fourth Hour  Trouble  Disability  
2             0        7           0  
3             1        6           0  
6             1        9           1  
7             0        8           1  
10            1        5           0

In [13]:
display(middle.head())

Student ID First Name Last Name  First Hour  Second Hour  Third Hour  \
0           0     Ximeno   Colombo           1            1           1   
1           1   Dorothea   Clayton           1            0           1   
4           4    Matilda   Solomon           0            1           1   
5           5    Kyllian   O'Berne           1            0           0   
8           8  Guadalupe    Lebrun           0            0           0   

   Fourth Hour  Trouble  Disability  
0            1       10           0  
1            1       10           0  
4            0        7           0  
5            0        1           0  
8            1        4           0

In [14]:
elemTeach = teachers[teachers['Grade'] == "elem"]
msTeach = teachers[teachers['Grade'] == "ms"]

In [15]:
display(elemTeach.head())

Teacher ID Grade  Certificate  Relief
0           0  elem            1       9
1           1  elem            0       5
4           4  elem            1       9
5           5  elem            0       7
6           6  elem            0       6

In [16]:
display(msTeach.head())

Teacher ID Grade  Certificate  Relief
2           2    ms            1       7
3           3    ms            0      10
7           7    ms            1      10
8           8    ms            0       6
9           9    ms            0       5

In [17]:
students['Grade'].value_counts()
# If we were to divide each of these by 4, the number of classes, we would have about:
# 10 students per middle school class (so we'd like a range that encompasses 10 but has some wiggle room: 9 & 12)
# and 5 students per elementary class (so we'd like a range that encompasses 5 but has some wiggle room: 5 & 8)

Grade
ms      39
elem    21
Name: count, dtype: int64

In [18]:
num_classes = 4
e = cp.Variable((len(elementary), num_classes), boolean = True)
m = cp.Variable((len(middle), num_classes), boolean = True)
te = cp.Variable((len(elemTeach), num_classes), boolean = True)
tm = cp.Variable((len(msTeach), num_classes), boolean = True)
x = cp.Variable(len(elementary), boolean = True)
y = cp.Variable(len(middle), boolean = True)

# Reference: https://github.com/samdavanloo/ISE-3230/blob/master/codes_in_CVXpy.ipynb : 3 Transportation
# Reference: https://www.statology.org/pandas-column-to-numpy-array/
# Availability matrices for elementary & middle school students.
E = elementary[['First Hour', 'Second Hour', 'Third Hour', 'Fourth Hour']].to_numpy()
M = middle[['First Hour', 'Second Hour', 'Third Hour', 'Fourth Hour']].to_numpy()

# Trouble and relief indicator arrays for elementary & middle school students & teachers.
HE = elementary['Trouble'].to_numpy()
HM = middle['Trouble'].to_numpy()
RE = elemTeach['Relief'].to_numpy()
RM = msTeach['Relief'].to_numpy()

# Disability and certificate indicator arrays for elementary & middle school students & teachers.
DE = elementary['Disability'].to_numpy()
CE = elemTeach['Certificate'].to_numpy()
DM = middle['Disability'].to_numpy()
CM = msTeach['Certificate'].to_numpy()

constraints = []
for i in range(len(elementary)):
    constraints.append(E[i,:] @ e[i,:].T == 1) # Each elementary student can attend at most one class.
for k in range(len(middle)):
    constraints.append(M[k,:] @ m[k,:].T == 1) # Each middle school student can attend at most one class.
for j in range(num_classes):
    constraints.append(5 <= cp.sum(e[:,j]))
    constraints.append(cp.sum(e[:,j]) <= 8) # Number of students per elementary class must be between 5 & 8.
    # This is because we would like to have a ratio of about two to three students per one teacher at most.
    constraints.append(9 <= cp.sum(m[:,j]))
    constraints.append(cp.sum(m[:,j]) <= 12) # Number of students per middle school class must be between 9 & 12.
    # Again, we want the ratio to be about two to three students per one teacher at most.
    constraints.append(cp.sum(te[:,j]) == 3) # Number of elementary teachers per elementary class must be 3.
    constraints.append(cp.sum(tm[:,j]) == 5) # Number of middle school teachers per middle school class must be 5.
    # If an elementary student with a disability is in class j, we also need at least one instructor with certification.
    constraints.append(x[:] <= DE @ e[:,j].T)
    constraints.append(DE @ e[:,j].T <= len(students)*y[0])
    constraints.append(x[:] <= CE @ te[:,j].T)
    # If a middle school student with a disability is in class j, we also need at least one instructor with certification.
    constraints.append(y[:] <= DM @ m[:,j].T)
    constraints.append(DM @ m[:,j].T <= len(students)*y[1])
    constraints.append(y[:] <= CM @ tm[:,j].T)

z = cp.sum(HE.T @ e) + cp.sum(HM.T @ m) - cp.sum(RE.T @ te) - cp.sum(RM.T @ tm) # Objective function
problem = cp.Problem(cp.Minimize(z), constraints) # We want to minimize our objective function.

In [19]:
problem.solve(solver=cp.GUROBI, verbose=True)

                                     CVXPY                                     
                                     v1.5.3                                    
(CVXPY) Nov 25 04:57:18 PM: Your problem has 356 variables, 572 constraints, and 0 parameters.
(CVXPY) Nov 25 04:57:18 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Nov 25 04:57:18 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Nov 25 04:57:18 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Nov 25 04:57:18 PM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Nov 25 04:57:18 PM: Compiling problem (target solver=GUROBI).

np.float64(65.0)

In [20]:
print("Objective function z =", z.value)
print("e =", e.value)
print("m =", m.value)
print("te =", te.value)
print("tm =", tm.value)
print("x =", x.value)
print("y =", y.value)

Objective function z = 65.0
e = [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
m = [[-0.  1. -0. -0.]
 [ 1.  0. -0. -0.]
 [-0. -0.  1. -0.]
 [ 1. -0. -0.  0.]
 [-0. -0.  0.  1.]
 [ 0.  1. -0. -0.]
 [-0.  1.  0.  0.]
 [-0.  0.  1. -0.]
 [ 0.  0.  1.  0.]
 [ 1.  0. -0. -0.]
 [ 0.  0.  1. -0.]
 [ 1.  0. -0. -0.]
 [-0.  1. -0.  0.]
 [ 0.  1.  0.  0.]
 [ 1. -0.  0.  0.]
 [-0. -0. -0.  1.]
 [-0.  0. -0.  1.]
 [ 0.  1. -0. -0.]
 [-0. -0.  1. -0.]
 [-0. -0.  0.  1.]
 [ 1. -0. -0.  0.]
 [-0.  0.  1. -0.]
 [ 0. -0.  1. -0.]
 [-0. -0. -0.  1.]
 [-0. -0. -0.  1.]
 [ 0. -0.  0.  1.]
 [ 0. -0.  1. -0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  0.  1.]
 [ 1. -0.  0.  0.]
 [ 1.  0. -0. -0.]
 [-0.  0.  1. -0.]
 [-0.  1. -0. -0.]
 [-0.  0.  1.  0.]
 [